---
title: "MS1 QC Report"
output:
  html_document: default
  pdf_document: default
date version: May 24, 2019
---

[//]: # (This sub-report contains metrics related to the performance of the MS1. This includes metrics using results of a SpectraST search blah blah. Metrics include the number of MS1 scans (and average per second), MS1 scan intensity distribution and median, MS1 frequency v retention time, and MS1 mass error.)


```{r Global Options, echo=FALSE}
knitr::opts_chunk$set(fig.width=5, fig.height=5, fig.align='center', warning=FALSE, message=FALSE, error=TRUE)
options(tinytex.verbose = TRUE)
```


```{r Extract instrumentInfo, eval=TRUE, echo=FALSE}
cat('Query file is ', make, ' ', model, '.', sep='')   # look up make and model of file for QC    
```


[//]: # (1. Extract QC values from query)

[//]: # (Here we extract and plot the TICs from the mzML files:)

```{r Extract TICs, eval=TRUE, echo=FALSE}

cat('Query TIC total area ', 100*sum(query_TIC_load)/sum(reference_TIC_load), '% of reference.',
    sep='')
cat('Est. amount injected ', AMOUNT_INJECTED*sum(query_TIC_load)/sum(reference_TIC_load), ' ng.',
    sep='')

plot(reference_TIC_load[,1], reference_TIC_load[,2], type="h", lwd=1, col='green', 
     xlab='retention time (min)', ylab='total ion current')
lines(query_TIC_load[,1], query_TIC_load[,2], type="h", lwd=1, col='blue')

```
\begin{center}Figure 1: Total ion chromatograms of reference (green) and query (blue).\end{center}


[//]: # (Here we extract mass error information from the mzID file:)

```{r Calculate average mass error using PSMs, , eval=TRUE, echo=FALSE}
cat('Average MS1 mass error: ', signif(1e6*mean_mz_error, digits=2), ' ppm.', sep='')

hist(1e6*mz_error[abs(mz_error)<0.05]/mz[abs(mz_error)<0.05], breaks = 1000, main = 'ppm error', xlab = 'ppm', xlim = c(-25,25) )

```
\begin{center}Figure 2: ppm error.\end{center}


```{r Plot error v m/z, eval=TRUE, echo=FALSE}
plot(mz, 1e6*mz_error/mz, col=alpha('blue', 2), pch='.', ylim = c(-10,10), xlab='AvePrecursorMz', ylab='MassDiff (in ppm)')

```
\begin{center}Figure 3: ppm error with m/z.\end{center}