---
title: "MS2 QC Report"
output:
  html_document: default
  pdf_document: default
date version: May 23, 2019
---

[//]: # (This sub-report contains metrics related to the performance of the MS2. This includes metrics using the results of a SpectraST search. Metrics include the number of MS2 scans (and average per second), MS2 scan intensity distribution and median, MS2 frequency v retention time, MS2 mass error, fill time (for trap instruments) v. MS2/PSM counts or v. isolation %, and MS2 identifications or features/time unit. The reference used in the following is a typical run of 200 ng HeLa digest against the given LC method.)


```{r Global Options, echo=FALSE}
knitr::opts_chunk$set(fig.width=5, fig.height=5, fig.align='center', warning=FALSE, message=FALSE, error=TRUE)
options(tinytex.verbose = TRUE)
```


```{r Extract instrumentInfo, eval=TRUE, echo=FALSE}
cat('Query file is ', make, ' ', model, '.', sep='')   # look up make and model of file for QC    
```


[//]: # (1. Extract QC values from SpectraST search)

[//]: # (Here we extract the number of estimated correct PSMs:)

```{r Extract PSMs, eval=TRUE, echo=FALSE}
PSMs <- c(nrow(psms(reference_ids)), nrow(psms(query_ids)))
barplot(PSMs, names.arg=c('reference','query'), col=c("green","blue"),
        ylab='PSMs (p>=0.95)')

```
\begin{center}Figure 1: Number of PSMs from SpectraST library search of reference (green) and query (blue).\end{center}
