---
title: "Source QC Report"
output:
  html_document: default
  pdf_document: default
date version: May 1, 2019
---

[//]: # (This sub-report contains metrics related to the performance of the source. This includes metrics such as TIC Signal, max/median TIC values, peak capacity (function of gradient length, PSMs and the FWHM of PSMs), MS1 dynamic range, and an evaluation of peak instability (or sputtering).)

```{r Global Options, echo=FALSE}
knitr::opts_chunk$set(fig.width=5, fig.height=5, fig.align='center', warning=FALSE, message=FALSE, error=TRUE)
options(tinytex.verbose = TRUE)
```


[//]: # (1. Load R packages and specify the search parameters and sequence database)

```{r Setup, echo=FALSE}
library(mzR)
library(scales)
library(XML)
library(pepXMLTab)
library(ggplot2)

# Commented out lines must be set before render call
QUERY <- '2018-10-18_HeLa_OTOT'                             # query for QC
#OUTPUT_DIR <- '/tmp/lkjdflkj'
MZML_DIR <- 'C:/TPP/data/Ben'

# The following are hard coded for now
REFERENCE <- '2018-10-15_HeLa_OTOT'                          # reference (could be local)
AMOUNT_INJECTED <- 200                                       # ng HeLa injected (reference)
SPECTRAST_LIBRARY <- '/data/HeLa.splib'                      # HeLa library
FASTA_FILE <- '/data/up000005640.fasta'                      # sequence database
mzml_file <- paste(MZML_DIR,'/',QUERY,'.mzML',sep='')
# cat('mzML file is',mzml_file)
```


[//]: # (2. Look up instrument manufacturer and model from query mzML file)

[//]: # (Here we read in instrument metadata from the mzML file using the mzR package) 

```{r Compare signal stability, echo=FALSE}
# reference_file <- openMSfile(paste(REFERENCE, '.mzML', sep=''))
# query_file <- openMSfile(paste(QUERY, '.mzML', sep=''))

# cat <QUERY>.mzML | grep MS:1000285 | awk '{gsub("value=\"",""); gsub("\"/>",""); print $7}' > QUERY_TIC.txt
# cat <REFERENCE>.mzML | grep MS:1000285 | awk '{gsub("value=\"",""); gsub("\"/>",""); print $7}' > REFERENCE_TIC.txt

query_TIC<-read.csv('QUERY_TIC.txt')
reference_TIC<-read.csv('REFERENCE_TIC.txt')

# query_TIC <- query_TIC*rnorm(dim(query_TIC)[1], mean=1, sd=1)

x <- query_TIC[,1]
# x <- x*rnorm(length(x), mean=1, sd=0.2)
# plot(1:length(x),x,type='l')
query_cor <- cor(x[-length(x)],x[-1])
x <- reference_TIC[,1]
reference_cor <- cor(x[-length(x)],x[-1])

barplot(c(reference_cor, query_cor), names.arg=c('reference','query'), col=c("green","blue"),
        ylab='signal stability', ylim=c(0,1))
```
\begin{center}Figure 1: Signal stability of reference (green) and query (blue).\end{center}
